const employeeList = [
    {
        name: 'Amma Lee',
        email: 'amma.lee@artlead.ca',
        position: "Head Manager",
        photoURL: '/static/logo.svg',
        status: "active",
        phone: "272-940-8266",
        hasAccess: true,
        accessLevel: 2,
        password: "123",
        balance: 0,
    
    },
    {
        name: 'Leatrice Handler',
        email: 'leatrice.handler@artlead.ca',
        position: "Manager",
        photoURL: '/static/logo.svg',
        status: "active",
        phone: "272-940-8266",
        hasAccess: true,
        accessLevel: 1,
        password: "123",
        balance: 0,
    },
    {
        name: 'Marine Mooslin',
        email: 'marine.mooslin@artlead.ca',
        position: "Instructor",
        photoURL: '/static/logo.svg',
        status: "active",
        phone: "272-940-8266",
        hasAccess: true,
        accessLevel: 0,
        password: "123",
        balance: 0,
    },
]